### ISSUE TITLE
erroneous example of `offsetof` usage in example 9.1

### ISSUE THREAD

**Issue by RossBencina** [wardvanwanrooij/thecbook#10]
The example code of example 9.1 is incorrect, because the first parameter to `offsetof` must name a type, not a variable. Consequently, the explanatory text following the example is also incorrect.

Here is the current book version (from the .pdf, "changes up to 2020-07-21"):

```
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>

main()
{
	size_t distance;
	struct x {
		int a, b, c;
	} s_tr;

	distance = offsetof(s_tr, c);
	printf("Offset of x.c is %lu bytes\n", (unsigned long)distance);

	exit(EXIT_SUCCESS);
}
```
> The expression s_tr.c must be capable of evaluation as an address constant (see
Chapter 6). If the member whose offset you want is a bitfield, then you’re out of
luck; offsetof has undefined behaviour in that case.

---

There are two ways to fix the code with a minimal change:

### Version 1:

```
- struct x {
+ typedef struct x {
```
this will make s_tr a type.

### Version 2:
```
- 	distance = offsetof(s_tr, c);
+ 	distance = offsetof(struct x, c);
```

Personally I would suggest "version 2" since it avoids introducing the concept of typedefs.

"Version 2" is the way that the example is given in The Annotated ANSI Standard (ANSI/ISO 9899-1990) Annotated by Herbert Schildt.

I don't have a suggestion for fixing the text, but simply note that the sentence *"The expression s_tr.c must be capable of evaluation as an address constant"* is incorrect.

**Comment by wardvanwanrooij** [comment]
Thank you for your issue reporting. After deliberation, I have decided to completely delete the sentence "The expression s_tr.c must be capable of evaluation as an address constant".
