### ISSUE TITLE
obvious typos in example C source code

### ISSUE THREAD

**Issue by RossBencina** [wardvanwanrooij/thecbook#11]
You may be interested that I have posted relevant fixes to the source code in the associated repo https://github.com/Amarok24/The_C_Book__Banahan

These are all obvious typos in the source code. I have since checked the book PDF and the typos are present there too:

https://github.com/Amarok24/The_C_Book__Banahan/pull/1/files

https://github.com/Amarok24/The_C_Book__Banahan/pull/2/files (see PR description for ISO standard reference)

**Comment by wardvanwanrooij** [comment]
Thanks for the error corrections and heads-up. I have incorporated these changes and made a new release.
