### ISSUE TITLE
extra spaces between all characters (copy/search)

### ISSUE THREAD

**Issue by Gendric** [wardvanwanrooij/thecbook#8]
Hi,

For some reason some pdf readers (like Sumatrapdf) or pdf tools (like mupdf) cannot properly assemble words out of characters found in the document, instead each character is considered a single word, with an extra space character added in the middle. Here is an example of text I get by either selecting and copying under a pdf reader, or by converting to text with mupdf:

```
Th e r e ’ s a
s e t o f g u i d e l i n e s f o r h o w t o
g e t
t h e
r e s u l t s t h a t a r e
m
o s t o f t e n
wa n t e d
f r o m
m u l t i - fi l e
c o n s t r u c t i o n , a n d
a
g o o d
d e a l
```

This make things like searching text not working, unless you add spaces. For example to quickly find the chapter dealing with strings one could search "s t r c p y" instead of "strcpy". The problem does not appear with all readers, for example Google Chrome will properly find the string without the extra spaces.

Thanks a lot for the pdf, anyway. :)
g.

**Comment by wardvanwanrooij** [comment]
This is a known issue with sumatrapdf https://github.com/sumatrapdfreader/sumatrapdf/issues/1651

**Comment by Gendric** [comment]
Understood. Thank you for your answer. :)
