### ISSUE TITLE
Extra {} in the middle of bit shift operator

### ISSUE THREAD

**Issue by cabanmichal** [wardvanwanrooij/thecbook#9]
Hi,

there's an extra pair of braces between the first and the second angle bracket of the bit shift operator.

https://github.com/wardvanwanrooij/thecbook/blob/b60be9fba6ef0a402ad841c1b383c8a3cb20a148/book.tex#L3432

**Comment by wardvanwanrooij** [comment]
Thank you for reporting this issue, I fixed it in the source code.
